export const fruits = [
	{
		id: 1,
		name: "红富士苹果",
		englishName: "Apple",
		origin: "陕西·洛川",
		category: "apple",
		price: 8.8,
		unit: "500g",
		image: "assets/images/apple.jpg",
	},
	{
		id: 2,
		name: "海南香蕉",
		englishName: "Banana",
		origin: "海南·三亚",
		category: "banana",
		price: 4.5,
		unit: "500g",
		image: "assets/images/banana.jpg",
	},
	{
		id: 3,
		name: "江西脐橙",
		englishName: "Orange",
		origin: "江西·赣州",
		category: "orange",
		price: 6.9,
		unit: "500g",
		image: "assets/images/orange.jpg",
	},
	{
		id: 4,
		name: "丹东草莓",
		englishName: "Strawberry",
		origin: "辽宁·丹东",
		category: "strawberry",
		price: 22,
		unit: "500g",
		image: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=600&h=450&fit=crop&auto=format",
	},
	{
		id: 5,
		name: "吐鲁番葡萄",
		englishName: "Grape",
		origin: "新疆·吐鲁番",
		category: "grape",
		price: 12.5,
		unit: "500g",
		image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&h=450&fit=crop&auto=format",
	},
	{
		id: 6,
		name: "宁夏西瓜",
		englishName: "Watermelon",
		origin: "宁夏·中卫",
		category: "watermelon",
		price: 3.2,
		unit: "500g",
		image: "assets/images/watermelon.jpg",
	},
	{
		id: 7,
		name: "台湾凤梨",
		englishName: "Pineapple",
		origin: "台湾·屏东",
		category: "pineapple",
		price: 9.9,
		unit: "个",
		image: "assets/images/pineapple.jpg",
	},
	{
		id: 8,
		name: "海南芒果",
		englishName: "Mango",
		origin: "海南·三亚",
		category: "mango",
		price: 15.8,
		unit: "500g",
		image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&h=450&fit=crop&auto=format",
	},
	{
		id: 9,
		name: "智利车厘子",
		englishName: "Cherry",
		origin: "智利·圣地亚哥",
		category: "cherry",
		price: 39.9,
		unit: "500g",
		image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=600&h=450&fit=crop&auto=format",
	},
	{
		id: 10,
		name: "新西兰奇异果",
		englishName: "Kiwi",
		origin: "新西兰·蒂普基",
		category: "kiwi",
		price: 11.5,
		unit: "个",
		image: "https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?w=600&h=450&fit=crop&auto=format",
	},
	{
		id: 11,
		name: "奉化水蜜桃",
		englishName: "Peach",
		origin: "浙江·奉化",
		category: "peach",
		price: 14,
		unit: "500g",
		image: "https://images.unsplash.com/photo-1629828874514-c1e5103f2150?w=600&h=450&fit=crop&auto=format",
	},
	{
		id: 12,
		name: "东北蓝莓",
		englishName: "Blueberry",
		origin: "黑龙江·大兴安岭",
		category: "blueberry",
		price: 28,
		unit: "125g",
		image: "https://images.unsplash.com/photo-1594002348772-bc0cb57ade8b?w=600&h=450&fit=crop&auto=format",
	},
];

export const categoryNames = {
	apple: "苹果",
	banana: "香蕉",
	blueberry: "蓝莓",
	cherry: "车厘子",
	grape: "葡萄",
	kiwi: "奇异果",
	mango: "芒果",
	orange: "橙子",
	peach: "桃子",
	pineapple: "凤梨",
	strawberry: "草莓",
	watermelon: "西瓜",
};
